### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by karkarl** [microsoft/WinUI-Gallery#1279]
Refactor WinUI-Gallery codebase:

```[tasklist]
### Tasks
- [x] Remove unused code
- [x] remove outdated ThemeResources
- [x] Proper xaml formatting
- [x] Proper class name / namespaces
- [x] Accessibility pass
- [x] Clean out unnecessary branches
- [x] Re-name `NewControls*` to `Home`
- [ ] https://github.com/microsoft/WinUI-Gallery/issues/1445
- [ ] https://github.com/microsoft/WinUI-Gallery/issues/1542
```

**Comment by Jay-o-Way** [comment]
Spring clean-up 🧹🪣🧽😛

**Comment by Jay-o-Way** [comment]
@niels9001  Would this include - for example - the following?
https://github.com/microsoft/WinUI-Gallery/blob/0a300bf69a51cf7684e93d95d89d9375130738f3/WinUIGallery/SettingsPage.xaml#L12C2-L20

Those numbers are not by the book; the elements (TextBlock) can probably be replaced with more modern implementations via SettingsGroup (Header)

**Comment by karkarl** [comment]
> 

Yes - the idea is to have WinUI Gallery also be a useful repo to refer to for best coding practices. That includes updating redundant xaml.

**Comment by Jay-o-Way** [comment]
Also a nit I found: https://github.com/microsoft/WinUI-Gallery/blob/0a300bf69a51cf7684e93d95d89d9375130738f3/WinUIGallery/SectionPage.xaml#L40
is unneeded - actually conflicting with line 49: `Style="{StaticResource TitleTextBlockStyle}"`
