### ISSUE TITLE
CI: Add debug & release configured CI pipeline

### ISSUE THREAD

**Issue by 0x5bfa** [microsoft/WinUI-Gallery#1302]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

I would rather add CI pipeline, so the team won't be caught build errors, automation errors. 

### Windows version

Insider Build (xxxxx)

```[tasklist]
### Tasks
- [ ] Configure in Azure DevOps
- [ ] Add Debug & Release build configururations in the CI strategy
- [ ] Add UI Automation test
- [ ] Add Unit test
```

**Comment by chingucoding** [comment]
Would you say this is sufficiently covered by #1289 and #1024?

**Comment by 0x5bfa** [comment]
Omg. Yes, I'm sorry that I didn't check if there's any duplicates.
