### ISSUE TITLE
Pipeline Migration to OneBranch

### ISSUE THREAD

**Issue by karkarl** [microsoft/WinUI-Gallery#1520]
Internal Bug [49424052](https://microsoft.visualstudio.com/OS/_workitems/edit/49424052)
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/WinUI-Gallery/issues/1025
- [ ] https://github.com/microsoft/WinUI-Gallery/issues/110
- [ ] https://github.com/microsoft/WinUI-Gallery/issues/1340
```
