### ISSUE TITLE
Work Tracking: Solution-wide code style application

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/WinUI-Gallery#363]
This issue exists to track work items related to solution-wide code style application.

## 1. Adopt a minimal EditorConfig

- [x] Make the decision to start implementing solution-wide code style rules
- [x] Agree on rules to include in the minimal EditorConfig
- [x] Add the minimal EditorConfig to the solution

### Formatting

- [ ] Decide on best approach for resolving the 38 formatting rules (commit/PR structure)

### Naming

- [ ] dotnet_naming_symbols.static_fields.required_modifiers

### Language Features

- [x] IDE0016: Use throw expressions to simplify null checks
- [x] IDE0017: Use object initializers
- [x] IDE0018: Variable declaration can be inlined
- [x] IDE0019: Use pattern matching over as with null check
- [x] IDE0028: Use collection initializers
- [x] IDE0049: Use type keywords
- [x] IDE1005: Delegate invocation can be simplified
- [x] IDExxxx: dotnet_style_explicit_tuple_names
- [x] IDExxxx: dotnet_style_null_propagation
- [x] IDExxxx: dotnet_style_coalesce_expression
- [x] IDExxxx: csharp_style_pattern_matching_over_is_with_cast_check

## 3. Switch to an EditorConfig that will eventually address all built-in rules

- [ ] Agree on rules to include in the initial version of this EditorConfig (note: this is not meant to be the final/complete ruleset, rules will rather be added over time as decisions are made on how to configure them)
- [ ] Swap the old EditorConfig with the new version

## 4. Resolve all built-in rule violations

**Comment by chingucoding** [comment]
@kmgallahan I assume you are not looking to continue working on this issue right? Would you be fine if this issue was closed than?

**Comment by kmgallahan** [comment]
@chingucoding

I started this effort because:

* I love using code analyzers and editorconfig files to standardize and improve my code
* I hate glancing at VS Error List windows and seeing dozens to hundreds of ignored warnings and messages

The idea was to create a somewhat standardized editorconfig that could be used for a few public-facing MS projects, and perhaps community projects as well.

However, the large number of analyzers combined with the friction of implementing changes made this painful, and that was just with the WinUI 2 Gallery 😅.

What are your thoughts on the subject?

**Comment by chingucoding** [comment]
I totally agree how great this can be, especially being able to see the list of errors, warnings and notifications going done. 

The best way moving forward would probably be merging this issue with others concerning warnings and editorconfig and have an issue that is tracking all that is necessary. However, of course I would defer to @karkarl on this matter.

Do you think this would be a suitable way moving forward and would you like to continue working on this matter @kmgallahan ?

**Comment by kmgallahan** [comment]
@chingucoding 

I don't plan to spend more time in this area any time soon. 

I'd recommend that the maintainers of the WinUI Gallery (?), WCT Sample App & Toolkit Labs Gallery (@michael-hawker ?), and MVVM Toolkit Sample App (@Sergio0694 ?) attempt to agree on a common `.editorconfig` file to share and follow.

If this can be done then perhaps it could spread to other MS WinUI apps and beyond.

I'll go ahead and close the issue.

**Comment by michael-hawker** [comment]
Hmmm, I thought there was an issue for this also in the platform repo somewhere? This is the only other one I can find though: https://github.com/microsoft/microsoft-ui-xaml/issues/1098

Definitely agree that it'd be helpful to have common patterns that are enforced across different repositories.

The Toolkit generally tries to follow most of the general .NET/C# guidance in these regards, and I believe we've encoded most of those in our `.editorconfig` files. They're generally pretty easy to add, and VS does provide fixes for a lot of them to apply en-masse.
